runtime: nodejs20
env: standard
instance_class: F2

# Include Python runtime for scan1Controller
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "20.0.0"

# Install Python dependencies
build_env_variables:
  GOOGLE_NODE_RUN_SCRIPTS: "npm run install:python-deps"

handlers:
  # Serve static files from /css
  - url: /css
    static_dir: public/css
    secure: always

  # Serve static files from /js
  - url: /js
    static_dir: public/js
    secure: always

  # Serve static files from /images
  - url: /images
    static_dir: public/images
    secure: always

  # Serve static files from /static
  - url: /static
    static_dir: public
    secure: always

  # Serve static files from /public
  - url: /public
    static_dir: public
    secure: always

  # Serve static files from root
  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|json))$
    static_files: public/\1
    upload: public/.*\.(js|css|png|jpg|jpeg|gif|ico|json)$
    secure: always

  # Serve all other requests with the app
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"
  API_URL: "https://backv2-app-brfi73d4ra-zf.a.run.app"
  PORT: "8080"
  UPLOAD_FOLDER: "/tmp/uploads"
  TEMP_FOLDER: "/tmp/temp"
  RESULTS_FOLDER: "/tmp/results"
  SUPABASE_URL: "https://dnjnsotemnfrjlotgved.supabase.co"
  USE_MOCK_API: "false"
  PYTHONPATH: "/usr/local/lib/python3/site-packages:/usr/local/lib/python3.9/site-packages:/usr/local/lib/python3.10/site-packages:/usr/local/lib/python3.11/site-packages"
  STORAGE_BUCKET: "backv2-documents"
  ENABLE_UPLOAD_FORM: "true"
  ENABLE_CHAT_INTERFACE: "true"
  ENABLE_ANALYTICS: "true"
  ENABLE_EXPORT: "true"
  ENABLE_SCAN1: "true"
  SCAN1_API_BASE_URL: "https://api.findoc-scan1.com/v1"
  SCAN1_ENHANCED_PROCESSING: "true"

includes:
  - secret.yaml

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_concurrent_requests: 50
