steps:
  # Print directory contents for debugging
  - name: 'gcr.io/cloud-builders/bash'
    args: ['ls', '-la']
  
  # Install dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  
  # Create a script to ensure UI components are properly included
  - name: 'gcr.io/cloud-builders/bash'
    args:
      - '-c'
      - |
        echo "Ensuring UI components are properly included..."
        mkdir -p public/js
        echo "UI components directory created"
        ls -la public/js
  
  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backv2-app', '.']
  
  # Push the container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/backv2-app']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'backv2-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/backv2-app'
      - '--region'
      - 'me-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/backv2-app'
