steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']

  # Copy server-enhanced.js to server.js
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cp server-enhanced.js server.js
        echo "Copied server-enhanced.js to server.js"

  # Verify critical files exist
  - name: 'ubuntu'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Verifying critical files..."
        if [ ! -f "server.js" ]; then
          echo "Error: server.js not found"
          exit 1
        fi
        if [ ! -f "app.yaml" ]; then
          echo "Error: app.yaml not found"
          exit 1
        fi
        if [ ! -f "middleware/enhanced-simple-injector.js" ]; then
          echo "Error: middleware/enhanced-simple-injector.js not found"
          exit 1
        fi
        if [ ! -f "middleware/ui-components-validator.js" ]; then
          echo "Error: middleware/ui-components-validator.js not found"
          exit 1
        fi
        echo "All critical files verified"

  # Deploy to App Engine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to App Engine..."
        gcloud app deploy app.yaml --quiet

# Timeout for the entire build
timeout: '1800s'
