
version: '3'
services:
  test-runner:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    command: >
      bash -c "
        apt-get update &&
        apt-get install -y wget gnupg ca-certificates procps libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxi6 libxtst6 libnss3 libcups2 libxss1 libxrandr2 libasound2 libatk1.0-0 libatk-bridge2.0-0 libpangocairo-1.0-0 libgtk-3-0 libgbm1 &&
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&
        echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' > /etc/apt/sources.list.d/google.list &&
        apt-get update &&
        apt-get install -y google-chrome-stable &&
        npm install puppeteer &&
        mkdir -p chat-test-screenshots &&
        chmod 777 chat-test-screenshots &&
        node puppeteer-chat-document-test.js
      "
    environment:
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - IN_DOCKER=true
      - HOST_URL=http://host.docker.internal:8080
