version: '3'
services:
  findoc-analyzer:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    environment:
      - NODE_ENV=production
