version: '3.8'

services:
  findoc-rag:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - UPLOAD_FOLDER=/app/uploads
      - TEMP_FOLDER=/app/temp
      - RESULTS_FOLDER=/app/results
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./results:/app/results
    restart: unless-stopped
