# Use a smaller base image for the production build
FROM node:18-alpine

WORKDIR /app

# Set environment variables
ENV NODE_ENV=production
ENV PORT=3002

# Copy the server-static.js file and index.html
COPY server-static.js ./server.js
COPY index.html ./index.html

# Expose the port the app will run on
EXPOSE 3002

# Set the command to run the app
CMD ["node", "server.js"]
