# Use a smaller base image for the production build
FROM node:18-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY package-express.json ./package.json

# Install dependencies
RUN npm install

# Copy the server.js file and public directory
COPY server-express.js ./server.js
COPY public ./public

# Expose the port the app will run on
EXPOSE 3002

# Set environment variables
ENV NODE_ENV=production
ENV PORT=3002

# Set the command to run the app
CMD ["node", "server.js"]
