name: Deploy Financial Document Processor to Google Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'financial_document_processor/**'
      - 'financial_document_processor_v2.py'
      - 'document_structure_analyzer.py'
      - 'enhanced_table_extractor.py'
      - 'pattern_based_extractor.py'
      - 'entity_relationship_modeler.py'
      - 'hierarchical_data_parser.py'
      - 'multi_stage_validator.py'
      - 'structured_products_handler.py'
      - 'isin_security_extractor.py'
      - 'asset_allocation_deduplicator.py'
      - 'comprehensive_report_generator.py'
      - 'google_cloud_deployment.py'
      - 'Dockerfile.financial'
  workflow_dispatch:

env:
  PROJECT_ID: github-456508
  SERVICE_NAME: financial-document-processor
  SERVICE_NAME_V2: financial-document-processor-v2
  REGION: me-west1

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker

      - name: Build and Push V1 Container
        run: |-
          cd financial_document_processor
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }} .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME:${{ github.sha }}

      - name: Build and Push V2 Container
        run: |-
          docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME_V2:${{ github.sha }} -f Dockerfile.financial .
          docker push gcr.io/$PROJECT_ID/$SERVICE_NAME_V2:${{ github.sha }}

      - name: Deploy V1 to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
            OPENROUTER_MODEL=${{ secrets.OPENROUTER_MODEL }}
            LOG_LEVEL=INFO

      - name: Deploy V2 to Cloud Run
        id: deploy_v2
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ${{ env.SERVICE_NAME_V2 }}
          region: ${{ env.REGION }}
          image: gcr.io/${{ env.PROJECT_ID }}/${{ env.SERVICE_NAME_V2 }}:${{ github.sha }}
          env_vars: |
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}
            OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}
            OPENROUTER_MODEL=${{ secrets.OPENROUTER_MODEL }}
            LOG_LEVEL=INFO

      - name: Show Output
        run: |
          echo "V1 URL: ${{ steps.deploy.outputs.url }}"
          echo "V2 URL: ${{ steps.deploy_v2.outputs.url }}"
