steps:
  # Print directory structure for debugging
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['-c', 'ls -la && echo "Current directory: $(pwd)"']

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/devdocs-app:$COMMIT_SHA', './DevDocs']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/devdocs-app:$COMMIT_SHA']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'devdocs-app'
      - '--image=gcr.io/$PROJECT_ID/devdocs-app:$COMMIT_SHA'
      - '--region=me-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--set-env-vars=NODE_ENV=production'

# Store images in Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/devdocs-app:$COMMIT_SHA'
