runtime: nodejs18

instance_class: F2

env_variables:
  NODE_ENV: "production"
  SUPABASE_URL: "https://dnjnsotemnfrjlotgved.supabase.co"
  SUPABASE_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRuam5zb3RlbW5mcmpsb3RndmVkIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTczOTY0OTY4NiwiZXhwIjoyMDU1MjI1Njg2fQ.CSCEGIYPEVwKKlPRerEyEHkXP6Xz3rx3qviMGxdiZYs"
  JWT_SECRET: "findoc-secret-key"
  # API keys configuration
  # Gemini API key from Secret Manager
  GEMINI_API_KEY: "sm://gemini-api-key"
  # OpenRouter API key from Secret Manager
  OPENROUTER_API_KEY: "sm://openrouter-api-key"
  # Set to "true" to use OpenRouter API (recommended as it's working)
  USE_OPENROUTER: "true"
  UPLOAD_FOLDER: "/tmp"
  TEMP_FOLDER: "/tmp"
  RESULTS_FOLDER: "/tmp"
  PORT: "8080"

handlers:
  - url: /api/.*
    script: auto
    secure: always
  - url: /static
    static_dir: public
    secure: always
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 5
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: 100ms
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

build_env_variables:
  NODE_ENV: "production"

# No Secret Manager configuration needed
