version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    volumes:
      - ./backv2-github/DevDocs/FinDocRAG/src:/app/src
      - ./uploads:/app/uploads
      - ./temp:/app/temp
      - ./results:/app/results
    environment:
      - UPLOAD_FOLDER=/app/uploads
      - TEMP_FOLDER=/app/temp
      - RESULTS_FOLDER=/app/results
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PORT=5000
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3002:3000"
    volumes:
      - ./backv2-github/DevDocs/frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
