runtime: nodejs18
env: standard
instance_class: F2

handlers:
  # Serve static files
  - url: /css
    static_dir: public/css
    secure: always

  - url: /js
    static_dir: public/js
    secure: always

  - url: /images
    static_dir: public/images
    secure: always

  # Serve all other requests with the app
  - url: /.*
    secure: always
    script: auto

env_variables:
  NODE_ENV: "production"
  UPLOAD_FOLDER: "/tmp/uploads"
  TEMP_FOLDER: "/tmp/temp"
  RESULTS_FOLDER: "/tmp/results"

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_concurrent_requests: 50
