name: Deploy to Cloud Run

on:
  push:
    branches: [ main, ui-modernization-2025 ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run:  < /dev/null | 
        echo "Running basic API tests..."
        node api-test.js
      
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    - name: Authorize Docker push
      run: gcloud auth configure-docker
      
    - name: Build and push Docker image
      id: docker_build
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/findoc-analyzer:${{ github.sha }}"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
        echo "::set-output name=image::$IMAGE_NAME"
        
    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: findoc-analyzer
        image: ${{ steps.docker_build.outputs.image }}
        region: us-central1
        env_vars: |
          NODE_ENV=production
          PORT=8080
        
    - name: Show Output
      run: echo ${{ steps.deploy.outputs.url }}
      
    - name: Test deployment
      run: |
        sleep 10  # Allow time for service to become available
        curl -s "${{ steps.deploy.outputs.url }}/api/health"
        
    - name: Post deployment summary
      uses: actions/github-script@v6
      with:
        script: |
          const url = "${{ steps.deploy.outputs.url }}";
          const sha = "${{ github.sha }}";
          const branch = "${{ github.ref_name }}";
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 Deployed to Cloud Run at [${url}](${url})
            
            **Branch:** ${branch}
            **Commit:** ${sha}
            
            ### Deployment Status
            | Resource | Status |
            | -------- | ------ |
            | App | ✅ Deployed |
            | API | ✅ Operational |
            
            To run verification test:
            \\`\\`\\`
            curl ${url}/api/health
            \\`\\`\\`
            `
          });
